# Generated by Django 3.0.3 on 2020-03-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200305_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
