# Generated by Django 3.0.3 on 2020-03-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
