# Generated by Django 3.0.3 on 2020-03-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200305_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
