# Generated by Django 3.0.3 on 2020-03-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
